"""Commercial contract checklist template — 12 canonical items (PRD §5e)."""

from app.generation.templates.types import ChecklistTemplate, TemplateItem

COMMERCIAL_CONTRACT = ChecklistTemplate.make(
    slug="commercial_contract",
    name="Commercial Contract",
    doc_type="commercial_contract",
    items=[
        TemplateItem(
            slug="parties",
            title="Parties identified",
            description="Parties to the agreement",
            category="Parties",
            required=True,
            sub_query="parties to the agreement; licensor licensee buyer seller contracting parties",
        ),
        TemplateItem(
            slug="effective_date",
            title="Effective date",
            description="Commencement or effective date of the agreement",
            category="Deadlines",
            required=True,
            sub_query="effective date commencement date agreement dated",
        ),
        TemplateItem(
            slug="term_duration",
            title="Term and duration",
            description="Duration of the agreement and any renewal provisions",
            category="Deadlines",
            required=True,
            sub_query="term of agreement duration initial term renewal",
        ),
        TemplateItem(
            slug="termination",
            title="Termination clauses",
            description="Grounds and process for termination",
            category="Other",
            required=True,
            sub_query="termination for cause termination for convenience notice of termination",
        ),
        TemplateItem(
            slug="confidentiality",
            title="Confidentiality provisions",
            description="Non-disclosure obligations on the parties",
            category="Disclosures",
            required=True,
            sub_query="confidential information non-disclosure proprietary information",
        ),
        TemplateItem(
            slug="ip_ownership",
            title="Intellectual property ownership",
            description="Ownership of IP rights and licensed materials",
            category="Other",
            required=True,
            sub_query="intellectual property rights ownership licensed materials work product",
        ),
        TemplateItem(
            slug="indemnification",
            title="Indemnification",
            description="Indemnification and hold-harmless obligations",
            category="Other",
            required=True,
            sub_query="indemnify hold harmless indemnification obligations",
        ),
        TemplateItem(
            slug="liability_limit",
            title="Limitation of liability",
            description="Liability cap and exclusion of consequential damages",
            category="Financial Terms",
            required=True,
            sub_query="limitation of liability cap on damages consequential damages",
        ),
        TemplateItem(
            slug="governing_law",
            title="Governing law and jurisdiction",
            description="Choice of governing law and venue for disputes",
            category="Other",
            required=True,
            sub_query="governing law jurisdiction venue choice of law",
        ),
        TemplateItem(
            slug="notice_provisions",
            title="Notice provisions",
            description="How and where notices are to be given",
            category="Other",
            required=False,
            sub_query="notice address how notice given written notice",
        ),
        TemplateItem(
            slug="assignment",
            title="Assignment clause",
            description="Restrictions and permissions on assignment of rights",
            category="Other",
            required=False,
            sub_query="assignment transfer of rights successors",
        ),
        TemplateItem(
            slug="signatures",
            title="Signatures present",
            description="Executed signature blocks by authorised signatories",
            category="Signatures",
            required=True,
            sub_query="signed by signature block executed by",
        ),
    ],
)
